data_path: 'data/names.txt'
checkpoint_path: 'models/checkpoint.pt'

block_size: 3
emb_size: 10
n_hidden: 100

seed: 2147483647
gain: 1.0
max_steps: 100000
batch_size: 32

lr = 0.001

lr_init: 0.01
lr_final: 0.001
lr_decay_step: 20000

